// Liste complète des membres TENF avec leurs pseudos Discord et liens Twitch
export interface Member {
  discordUsername: string;
  twitchLogin: string;
  twitchUrl: string;
  displayName: string;
}

export const allMembers: Member[] = [
  { discordUsername: "NeXou31", twitchLogin: "nexou31", twitchUrl: "https://www.twitch.tv/nexou31", displayName: "NeXou31" },
  { discordUsername: "Clara", twitchLogin: "clarastonewall", twitchUrl: "https://www.twitch.tv/clarastonewall", displayName: "Clara" },
  { discordUsername: "Red_Shadow_31", twitchLogin: "red_shadow_31", twitchUrl: "https://www.twitch.tv/red_shadow_31", displayName: "Red_Shadow_31" },
  { discordUsername: "TheDark_Sand", twitchLogin: "thedark_sand", twitchUrl: "https://www.twitch.tv/thedark_sand", displayName: "TheDark_Sand" },
  { discordUsername: "Selena_Akemi", twitchLogin: "selena_akemi", twitchUrl: "https://www.twitch.tv/selena_akemi", displayName: "Selena_Akemi" },
  { discordUsername: "altheatroy", twitchLogin: "altheatroy", twitchUrl: "https://www.twitch.tv/altheatroy", displayName: "altheatroy" },
  { discordUsername: "Dylow95", twitchLogin: "dylow95", twitchUrl: "https://www.twitch.tv/dylow95", displayName: "Dylow95" },
  { discordUsername: "RubbyCrea", twitchLogin: "RubbyCrea", twitchUrl: "https://twitch.tv/RubbyCrea", displayName: "RubbyCrea" },
  { discordUsername: "BenZzOoTV", twitchLogin: "benzzootv", twitchUrl: "https://www.twitch.tv/benzzootv", displayName: "BenZzOoTV" },
  { discordUsername: "Livio_On", twitchLogin: "livio_on", twitchUrl: "https://www.twitch.tv/livio_on", displayName: "Livio_On" },
  { discordUsername: "MiSsLyliee", twitchLogin: "misslyliee", twitchUrl: "https://www.twitch.tv/misslyliee", displayName: "MiSsLyliee" },
  { discordUsername: "Yaya_TV", twitchLogin: "yaya_romali", twitchUrl: "https://www.twitch.tv/yaya_romali", displayName: "Yaya_TV" },
  { discordUsername: "Jenny31200", twitchLogin: "jenny31200", twitchUrl: "https://www.twitch.tv/jenny31200", displayName: "Jenny31200" },
  { discordUsername: "JALNNA", twitchLogin: "jalnna76", twitchUrl: "https://www.twitch.tv/jalnna76", displayName: "JALNNA" },
  { discordUsername: "kalyshin", twitchLogin: "kalyshin", twitchUrl: "https://www.twitch.tv/kalyshin", displayName: "kalyshin" },
  { discordUsername: "Thony1384", twitchLogin: "thony1384", twitchUrl: "https://www.twitch.tv/thony1384", displayName: "Thony1384" },
  { discordUsername: "Lilbaabs", twitchLogin: "lilbaabs", twitchUrl: "https://www.twitch.tv/lilbaabs", displayName: "Lilbaabs" },
  { discordUsername: "Nemsb2b", twitchLogin: "nemsb2b", twitchUrl: "https://www.twitch.tv/nemsb2b", displayName: "Nemsb2b" },
  { discordUsername: "MOUSSKEYKONG", twitchLogin: "mousskeykong", twitchUrl: "https://twitch.tv/mousskeykong", displayName: "MOUSSKEYKONG" },
  { discordUsername: "PIERROTOFFICIEL", twitchLogin: "pierrotofficiel", twitchUrl: "https://www.twitch.tv/pierrotofficiel", displayName: "PIERROTOFFICIEL" },
  { discordUsername: "LeDocMonky", twitchLogin: "ledocmonky", twitchUrl: "https://www.twitch.tv/ledocmonky", displayName: "LeDocMonky" },
  { discordUsername: "Tabs", twitchLogin: "tabs_up", twitchUrl: "https://www.twitch.tv/tabs_up", displayName: "Tabs" },
  { discordUsername: "𝖓𝖆𝖓𝖌𝖊𝖑89", twitchLogin: "loulangegaming", twitchUrl: "https://twitch.tv/loulangegaming", displayName: "LoulangeGaming" },
  { discordUsername: "𝐵𝑒𝑡𝑒_𝐹𝑒𝑟𝑜𝑐𝑒", twitchLogin: "bete_feroce", twitchUrl: "https://www.twitch.tv/bete_feroce", displayName: "Bete_Feroce" },
  { discordUsername: "[FLN] Flambouille", twitchLogin: "flanbouille", twitchUrl: "https://www.twitch.tv/flanbouille", displayName: "Flambouille" },
  { discordUsername: "ONIZUKA", twitchLogin: "onizuka2734", twitchUrl: "https://www.twitch.tv/onizuka2734", displayName: "ONIZUKA" },
  { discordUsername: "𝓔𝓶𝓲𝓵𝔂𝓢𝓲𝓶𝓼", twitchLogin: "emilysims76", twitchUrl: "https://www.twitch.tv/emilysims76", displayName: "EmilySims" },
  { discordUsername: "MaxRoRonoa22", twitchLogin: "maxroronoa22", twitchUrl: "https://www.twitch.tv/maxroronoa22", displayName: "MaxRoRonoa22" },
  { discordUsername: "Mcfly_59140", twitchLogin: "mcfly_59140", twitchUrl: "https://www.twitch.tv/mcfly_59140", displayName: "Mcfly_59140" },
  { discordUsername: "𝖦𝗂𝗅𝖻𝖾𝗋𝗍 𝖧𝗂𝗆𝖾.", twitchLogin: "Gilbert_hime", twitchUrl: "https://www.twitch.tv/Gilbert_hime", displayName: "Gilbert_Hime" },
  { discordUsername: "stormlight____", twitchLogin: "stormlight____", twitchUrl: "https://www.twitch.tv/stormlight____", displayName: "stormlight____" },
  { discordUsername: "Leviacarpe", twitchLogin: "leviacarpe", twitchUrl: "https://www.twitch.tv/leviacarpe", displayName: "Leviacarpe" },
  { discordUsername: "LeSpydyverse", twitchLogin: "lespydyverse", twitchUrl: "https://www.twitch.tv/lespydyverse", displayName: "LeSpydyverse" },
  { discordUsername: "𝔅𝔩𝔞𝔠𝔨𝔢𝔫𝔢𝔡𝔉𝔬𝔯𝔄𝔩𝔩", twitchLogin: "blackenedforall", twitchUrl: "https://www.twitch.tv/blackenedforall", displayName: "BlackenedForAll" },
  { discordUsername: "OnclesMarius", twitchLogin: "OnclesMarius", twitchUrl: "https://www.twitch.tv/OnclesMarius", displayName: "OnclesMarius" },
  { discordUsername: "H2_NarVaLo", twitchLogin: "h2_narvalo", twitchUrl: "https://www.twitch.tv/h2_narvalo", displayName: "H2_NarVaLo" },
  { discordUsername: "Etoras56", twitchLogin: "etoras56", twitchUrl: "https://www.twitch.tv/etoras56", displayName: "Etoras56" },
  { discordUsername: "Tania2507", twitchLogin: "tania2507", twitchUrl: "https://www.twitch.tv/tania2507", displayName: "Tania2507" },
  { discordUsername: "SallyRuby", twitchLogin: "sallyruby", twitchUrl: "https://www.twitch.tv/sallyruby", displayName: "SallyRuby" },
  { discordUsername: "Seykasuxkyas83", twitchLogin: "seykasuxkyas83", twitchUrl: "https://www.twitch.tv/seykasuxkyas83", displayName: "Seykasuxkyas83" },
  { discordUsername: "⭐ LYXO6Z ⭐", twitchLogin: "lyxo6z", twitchUrl: "https://www.twitch.tv/lyxo6z", displayName: "LYXO6Z" },
  { discordUsername: "mika17330", twitchLogin: "mika17330", twitchUrl: "https://www.twitch.tv/mika17330", displayName: "mika17330" },
  { discordUsername: "Zelephs", twitchLogin: "zelephs", twitchUrl: "https://www.twitch.tv/zelephs", displayName: "Zelephs" },
  { discordUsername: "Gagini_", twitchLogin: "gagini_", twitchUrl: "https://www.twitch.tv/gagini_", displayName: "Gagini_" },
  { discordUsername: "jogamerss", twitchLogin: "jogamerss", twitchUrl: "https://www.twitch.tv/jogamerss", displayName: "jogamerss" },
  { discordUsername: "Scor__pion", twitchLogin: "scor__pion4", twitchUrl: "https://www.twitch.tv/scor__pion4", displayName: "Scor__pion" },
  { discordUsername: "fouinaxx", twitchLogin: "fouinaxx", twitchUrl: "https://www.twitch.tv/fouinaxx", displayName: "fouinaxx" },
  { discordUsername: "KnuckyGP", twitchLogin: "knuckygp", twitchUrl: "https://twitch.tv/knuckygp", displayName: "KnuckyGP" },
  { discordUsername: "sigurdson", twitchLogin: "sigurdson64", twitchUrl: "https://www.twitch.tv/sigurdson64", displayName: "sigurdson" },
  { discordUsername: "mmesigurdson6451", twitchLogin: "mmesigurdson64", twitchUrl: "https://www.twitch.tv/mmesigurdson64", displayName: "mmesigurdson6451" },
  { discordUsername: "itslukastv_", twitchLogin: "nnotyi", twitchUrl: "https://www.twitch.tv/nnotyi", displayName: "itslukastv_" },
  { discordUsername: "yotox47", twitchLogin: "yotox47", twitchUrl: "https://www.twitch.tv/yotox47", displayName: "yotox47" },
  { discordUsername: "Fardezal", twitchLogin: "FardezalTV", twitchUrl: "https://www.twitch.tv/FardezalTV", displayName: "Fardezal" },
  { discordUsername: "Noxyre_TV", twitchLogin: "noxyre_tv", twitchUrl: "https://www.twitch.tv/noxyre_tv", displayName: "Noxyre_TV" },
  { discordUsername: "NesQuiik_s", twitchLogin: "nesquiik_s", twitchUrl: "https://www.twitch.tv/nesquiik_s", displayName: "NesQuiik_s" },
  { discordUsername: "Simon_le7", twitchLogin: "simon_le7", twitchUrl: "https://www.twitch.tv/simon_le7", displayName: "Simon_le7" },
  { discordUsername: "Kolomiso_twitch", twitchLogin: "kolomiso_twitch", twitchUrl: "https://www.twitch.tv/kolomiso_twitch", displayName: "Kolomiso_twitch" },
  { discordUsername: "Hellgate80", twitchLogin: "hellgate80", twitchUrl: "https://www.twitch.tv/hellgate80", displayName: "Hellgate80" },
  { discordUsername: "MajorMixo", twitchLogin: "majormixo", twitchUrl: "https://www.twitch.tv/majormixo", displayName: "MajorMixo" },
  { discordUsername: "bobman49100", twitchLogin: "bobman49100", twitchUrl: "https://www.twitch.tv/bobman49100", displayName: "bobman49100" },
  { discordUsername: "Rogue_Stapler", twitchLogin: "rogue_stapler", twitchUrl: "https://www.twitch.tv/rogue_stapler", displayName: "Rogue_Stapler" },
  { discordUsername: "PrincessEnuria_54", twitchLogin: "princessenuria_54", twitchUrl: "https://www.twitch.tv/princessenuria_54", displayName: "PrincessEnuria_54" },
  { discordUsername: "Missprissou96", twitchLogin: "missprissou96", twitchUrl: "https://www.twitch.tv/missprissou96", displayName: "Missprissou96" },
  { discordUsername: "patrick_patoix", twitchLogin: "patrick_patoix", twitchUrl: "https://www.twitch.tv/patrick_patoix", displayName: "patrick_patoix" },
  { discordUsername: "Jooblack__", twitchLogin: "jooblack__", twitchUrl: "https://www.twitch.tv/jooblack__", displayName: "Jooblack__" },
  { discordUsername: "SethTV1", twitchLogin: "sethtv1", twitchUrl: "https://www.twitch.tv/sethtv1", displayName: "SethTV1" },
  { discordUsername: "Roronoa22_", twitchLogin: "roronoa12_", twitchUrl: "https://www.twitch.tv/roronoa12_", displayName: "Roronoa22_" },
  { discordUsername: "Xloucs_Off", twitchLogin: "Xloucs_Off", twitchUrl: "https://www.twitch.tv/Xloucs_Off", displayName: "Xloucs_Off" },
  { discordUsername: "snoopyange", twitchLogin: "snoopyange87", twitchUrl: "https://www.twitch.tv/snoopyange87", displayName: "snoopyange" },
  { discordUsername: "TheBoss974HD", twitchLogin: "theboss974hd", twitchUrl: "https://www.twitch.tv/theboss974hd", displayName: "TheBoss974HD" },
  { discordUsername: "lephilosophe21", twitchLogin: "lephilosophe21", twitchUrl: "https://www.twitch.tv/lephilosophe21", displayName: "lephilosophe21" },
  { discordUsername: "Al4storTv", twitchLogin: "al4stortv", twitchUrl: "https://www.twitch.tv/al4stortv", displayName: "Al4storTv" },
  { discordUsername: "naaash137", twitchLogin: "naaash137", twitchUrl: "https://www.twitch.tv/naaash137", displayName: "naaash137" },
  { discordUsername: "Totoni112", twitchLogin: "totoni112", twitchUrl: "https://www.twitch.tv/totoni112", displayName: "Totoni112" },
  { discordUsername: "RoiSephiBoo", twitchLogin: "roisephiboo", twitchUrl: "https://www.twitch.tv/roisephiboo", displayName: "RoiSephiBoo" },
  { discordUsername: "kidoyuto92", twitchLogin: "kidoyuto92", twitchUrl: "https://www.twitch.tv/kidoyuto92", displayName: "kidoyuto92" },
  { discordUsername: "mat_le_suisse_gaming", twitchLogin: "mat_le_suisse_gaming", twitchUrl: "https://www.twitch.tv/mat_le_suisse_gaming", displayName: "mat_le_suisse_gaming" },
  { discordUsername: "DJOKUMA", twitchLogin: "djokuma", twitchUrl: "https://www.twitch.tv/djokuma", displayName: "DJOKUMA" },
  { discordUsername: "LeBerzerk", twitchLogin: "leberzerk", twitchUrl: "https://www.twitch.tv/leberzerk", displayName: "LeBerzerk" },
  { discordUsername: "AceMendosa", twitchLogin: "acemendosa", twitchUrl: "https://www.twitch.tv/acemendosa", displayName: "AceMendosa" },
  { discordUsername: "GhostBoarTV", twitchLogin: "GhostBoarTV", twitchUrl: "https://www.twitch.tv/GhostBoarTV", displayName: "GhostBoarTV" },
  { discordUsername: "NoxMower", twitchLogin: "noxmower", twitchUrl: "https://www.twitch.tv/noxmower", displayName: "NoxMower" },
  { discordUsername: "🐬 Rebelle_7DS 🐬", twitchLogin: "rebelle_7ds", twitchUrl: "https://www.twitch.tv/rebelle_7ds", displayName: "Rebelle_7DS" },
  { discordUsername: "siryubux", twitchLogin: "siryubux", twitchUrl: "https://www.twitch.tv/siryubux", displayName: "siryubux" },
  { discordUsername: "ZeroNova59", twitchLogin: "zeronova59", twitchUrl: "https://www.twitch.tv/zeronova59", displayName: "ZeroNova59" },
  { discordUsername: "Xxonto", twitchLogin: "xxonto", twitchUrl: "https://www.twitch.tv/xxonto", displayName: "Xxonto" },
  { discordUsername: "shirofairyy", twitchLogin: "shirofairyy", twitchUrl: "https://www.twitch.tv/shirofairyy", displayName: "shirofairyy" },
  { discordUsername: "LaCathoPhile", twitchLogin: "lacathophile", twitchUrl: "https://www.twitch.tv/lacathophile", displayName: "LaCathoPhile" },
  { discordUsername: "ZekPower", twitchLogin: "zekpower42", twitchUrl: "https://www.twitch.tv/zekpower42", displayName: "ZekPower" },
  { discordUsername: "Ensko", twitchLogin: "ensko34", twitchUrl: "https://twitch.tv/ensko34", displayName: "Ensko" },
  { discordUsername: "wirox104", twitchLogin: "wirox104", twitchUrl: "https://www.twitch.tv/wirox104", displayName: "wirox104" },
  { discordUsername: "Nico-73-79", twitchLogin: "nico_73_79", twitchUrl: "https://www.twitch.tv/nico_73_79", displayName: "Nico-73-79" },
  { discordUsername: "predix07", twitchLogin: "predix07", twitchUrl: "https://www.twitch.tv/predix07", displayName: "predix07" },
  { discordUsername: "Pix__tv", twitchLogin: "pix__tv", twitchUrl: "https://www.twitch.tv/pix__tv", displayName: "Pix__tv" },
  { discordUsername: "Cocolivia", twitchLogin: "cocolivia", twitchUrl: "https://www.twitch.tv/cocolivia", displayName: "Cocolivia" },
  { discordUsername: "lilicia62", twitchLogin: "lilicia62160", twitchUrl: "https://www.twitch.tv/lilicia62160", displayName: "lilicia62" },
  { discordUsername: "Cĥt¡Føน", twitchLogin: "chtifou95", twitchUrl: "https://www.twitch.tv/chtifou95", displayName: "Chtifou" },
  { discordUsername: "𝓜8 𝓣𝓲𝓫𝓸 🐝", twitchLogin: "pollentv_", twitchUrl: "https://www.twitch.tv/pollentv_", displayName: "M8_Tibo" },
  { discordUsername: "Le Sinistrement SINISTRE 33", twitchLogin: "lesinistre33", twitchUrl: "https://www.twitch.tv/lesinistre33", displayName: "Le_Sinistre_33" },
  { discordUsername: "Terprozer", twitchLogin: "terproze", twitchUrl: "https://www.twitch.tv/terproze", displayName: "Terprozer" },
  { discordUsername: "LeB1nx", twitchLogin: "leb1nx", twitchUrl: "https://www.twitch.tv/leb1nx", displayName: "LeB1nx" },
  { discordUsername: "lauxi_off", twitchLogin: "lauxi_off", twitchUrl: "https://www.twitch.tv/lauxi_off", displayName: "lauxi_off" },
  { discordUsername: "madara79ttv", twitchLogin: "madara79tv", twitchUrl: "https://www.twitch.tv/madara79tv", displayName: "madara79ttv" },
  { discordUsername: "oxi-wanted13", twitchLogin: "oxiwanted13", twitchUrl: "https://www.twitch.tv/oxiwanted13", displayName: "oxi-wanted13" },
  { discordUsername: "Izouzou", twitchLogin: "izouzou", twitchUrl: "https://www.twitch.tv/izouzou", displayName: "Izouzou" },
  { discordUsername: "Zer0Sang", twitchLogin: "zer0sang", twitchUrl: "https://www.twitch.tv/zer0sang", displayName: "Zer0Sang" },
  { discordUsername: "EnthisTV", twitchLogin: "enthistv", twitchUrl: "https://www.twitch.tv/enthistv", displayName: "EnthisTV" },
  { discordUsername: "Zylkao", twitchLogin: "zylkao", twitchUrl: "https://www.twitch.tv/zylkao", displayName: "Zylkao" },
  { discordUsername: "Anthony62221", twitchLogin: "antho62221", twitchUrl: "https://www.twitch.tv/antho62221", displayName: "Anthony62221" },
  { discordUsername: "3 cartes en main", twitchLogin: "trois_cartes_en_main", twitchUrl: "https://www.twitch.tv/trois_cartes_en_main", displayName: "3_cartes_en_main" },
  { discordUsername: "Mageekobus", twitchLogin: "mageekobus", twitchUrl: "https://www.twitch.tv/mageekobus", displayName: "Mageekobus" },
  { discordUsername: "hatsune_mikumiku", twitchLogin: "hastune_mikumiku", twitchUrl: "https://www.twitch.tv/hastune_mikumiku", displayName: "hatsune_mikumiku" },
  { discordUsername: "Lostenk56", twitchLogin: "lostenk56", twitchUrl: "https://www.twitch.tv/lostenk56", displayName: "Lostenk56" },
  { discordUsername: "Valkas7", twitchLogin: "valkas7", twitchUrl: "https://www.twitch.tv/valkas7", displayName: "Valkas7" },
  { discordUsername: "lalicornegeek", twitchLogin: "lalic0rn3geek", twitchUrl: "https://www.twitch.tv/lalic0rn3geek", displayName: "lalicornegeek" },
  { discordUsername: "Evan34740", twitchLogin: "evan34740", twitchUrl: "https://www.twitch.tv/evan34740", displayName: "Evan34740" },
  { discordUsername: "LudraTv", twitchLogin: "ludra_tv", twitchUrl: "https://www.twitch.tv/ludra_tv", displayName: "LudraTv" },
  { discordUsername: "Moustagaming93", twitchLogin: "moustagaming93", twitchUrl: "https://www.twitch.tv/moustagaming93", displayName: "Moustagaming93" },
  { discordUsername: "Face_BCD", twitchLogin: "face_bcd", twitchUrl: "https://twitch.tv/face_bcd", displayName: "Face_BCD" },
  { discordUsername: "Alx_r1v3r", twitchLogin: "alx_r1v3r", twitchUrl: "https://twitch.tv/alx_r1v3r", displayName: "Alx_r1v3r" },
  { discordUsername: "gingree.", twitchLogin: "gingree", twitchUrl: "https://www.twitch.tv/gingree", displayName: "gingree" },
  { discordUsername: "Bainetaine", twitchLogin: "bainetaine", twitchUrl: "https://www.twitch.tv/bainetaine", displayName: "Bainetaine" },
  { discordUsername: "Shiny_cat", twitchLogin: "shinycat1", twitchUrl: "https://www.twitch.tv/shinycat1", displayName: "Shiny_cat" },
  { discordUsername: "Aduken_TV", twitchLogin: "aduken_tv", twitchUrl: "https://www.twitch.tv/aduken_tv", displayName: "Aduken_TV" },
  { discordUsername: "Skadi Style", twitchLogin: "skadi_style", twitchUrl: "https://www.twitch.tv/skadi_style", displayName: "Skadi_Style" },
  { discordUsername: "Lafilledu_14", twitchLogin: "la_filledu14", twitchUrl: "https://twitch.tv/la_filledu14", displayName: "Lafilledu_14" },
  { discordUsername: "Vektor_live", twitchLogin: "vektor_live", twitchUrl: "https://www.twitch.tv/vektor_live", displayName: "Vektor_live" },
  { discordUsername: "Voodkas_", twitchLogin: "voodkas_", twitchUrl: "https://www.twitch.tv/voodkas_", displayName: "Voodkas_" },
  { discordUsername: "emms_twitch", twitchLogin: "emms_twitch", twitchUrl: "https://www.twitch.tv/emms_twitch", displayName: "emms_twitch" },
  { discordUsername: "SaraTatineQc", twitchLogin: "saratatineqc", twitchUrl: "https://www.twitch.tv/saratatineqc", displayName: "SaraTatineQc" },
  { discordUsername: "Fastcash", twitchLogin: "fastcash", twitchUrl: "https://www.twitch.tv/fastcash", displayName: "Fastcash" },
  { discordUsername: "wapitiroyale", twitchLogin: "wapitiroyale", twitchUrl: "https://www.twitch.tv/wapitiroyale", displayName: "wapitiroyale" },
  { discordUsername: "Tome_Huns", twitchLogin: "tome_huns", twitchUrl: "https://www.twitch.tv/tome_huns", displayName: "Tome_Huns" },
  { discordUsername: "Barnei", twitchLogin: "barneigaming", twitchUrl: "https://www.twitch.tv/barneigaming", displayName: "Barnei" },
  { discordUsername: "MojoSummerheart", twitchLogin: "mojosummerheart", twitchUrl: "https://www.twitch.tv/mojosummerheart", displayName: "MojoSummerheart" },
  { discordUsername: "Isa_chieuze_7DS", twitchLogin: "isa_chieuze_7DS", twitchUrl: "https://www.twitch.tv/isa_chieuze_7DS", displayName: "Isa_chieuze_7DS" },
  { discordUsername: "Afirics", twitchLogin: "afirics", twitchUrl: "https://www.twitch.tv/afirics", displayName: "Afirics" },
  { discordUsername: "Lilou", twitchLogin: "liloudraw", twitchUrl: "https://www.twitch.tv/liloudraw", displayName: "Lilou" },
  { discordUsername: "Lacøsteur", twitchLogin: "lacosteur___", twitchUrl: "https://www.twitch.tv/lacosteur___", displayName: "Lacosteuer" },
  { discordUsername: "gaara_san_84", twitchLogin: "gaara_san_84", twitchUrl: "https://www.twitch.tv/gaara_san_84", displayName: "gaara_san_84" },
  { discordUsername: "Darkins", twitchLogin: "darkinsomg", twitchUrl: "https://www.twitch.tv/darkinsomg", displayName: "Darkins" },
  { discordUsername: "Denivak", twitchLogin: "denivak", twitchUrl: "https://www.twitch.tv/denivak", displayName: "Denivak" },
  { discordUsername: "Le L Gaming", twitchLogin: "lelgamingandstreaming", twitchUrl: "https://www.twitch.tv/lelgamingandstreaming", displayName: "Le_L_Gaming" },
  { discordUsername: "ninie", twitchLogin: "lagameuseninie", twitchUrl: "https://www.twitch.tv/lagameuseninie", displayName: "ninie" },
  { discordUsername: "Falkone", twitchLogin: "falkonechannel", twitchUrl: "https://www.twitch.tv/falkonechannel", displayName: "Falkone" },
  { discordUsername: "flofaitdesvideo", twitchLogin: "flofaitdesvideo", twitchUrl: "https://www.twitch.tv/flofaitdesvideo", displayName: "flofaitdesvideo" },
  { discordUsername: "Ti'migu-nyan💙🐾😸🐾💙", twitchLogin: "miguwell1", twitchUrl: "https://www.twitch.tv/miguwell1", displayName: "Timigu_nyan" },
  { discordUsername: "Akaioh", twitchLogin: "akaioh_", twitchUrl: "https://www.twitch.tv/akaioh_", displayName: "Akaioh" },
  { discordUsername: "Mechant_karma", twitchLogin: "mechant_karma", twitchUrl: "https://www.twitch.tv/mechant_karma", displayName: "Mechant_karma" },
  { discordUsername: "Bear_krys", twitchLogin: "bear_krys", twitchUrl: "https://www.twitch.tv/bear_krys", displayName: "Bear_krys" },
  { discordUsername: "Mirajane", twitchLogin: "mirajane_18", twitchUrl: "https://www.twitch.tv/mirajane_18", displayName: "Mirajane" },
  { discordUsername: "Batje76", twitchLogin: "batje76", twitchUrl: "https://www.twitch.tv/batje76", displayName: "Batje76" },
  { discordUsername: "FrostyQuinn94", twitchLogin: "frostyquinn94_js", twitchUrl: "https://www.twitch.tv/frostyquinn94_js", displayName: "FrostyQuinn94" },
  { discordUsername: "zx_ced", twitchLogin: "zx_ced", twitchUrl: "https://www.twitch.tv/zx_ced", displayName: "zx_ced" },
  { discordUsername: "Mrnightshots", twitchLogin: "mrnightshots", twitchUrl: "https://www.twitch.tv/mrnightshots", displayName: "Mrnightshots" },
  { discordUsername: "Hugo2602c", twitchLogin: "hugo2602c", twitchUrl: "https://www.twitch.tv/hugo2602c", displayName: "Hugo2602c" },
  { discordUsername: "Caelestis.ttv", twitchLogin: "caelestis_ttv", twitchUrl: "https://www.twitch.tv/caelestis_ttv", displayName: "Caelestis_ttv" },
  { discordUsername: "Skar", twitchLogin: "skarpane", twitchUrl: "https://www.twitch.tv/skarpane", displayName: "Skar" },
  { discordUsername: "LaTaniereVerteTV", twitchLogin: "lataniereverte", twitchUrl: "https://www.twitch.tv/lataniereverte", displayName: "LaTaniereVerteTV" },
  { discordUsername: "MyrtilleTV", twitchLogin: "myrtilletv", twitchUrl: "https://www.twitch.tv/myrtilletv", displayName: "MyrtilleTV" },
  { discordUsername: "alicornedejais", twitchLogin: "alicornedejais", twitchUrl: "https://www.twitch.tv/alicornedejais", displayName: "alicornedejais" },
  { discordUsername: "aaabaddon", twitchLogin: "aaabaddoncroc2pomme", twitchUrl: "https://www.twitch.tv/aaabaddoncroc2pomme", displayName: "aaabaddon" },
  { discordUsername: "Fekferk hoshino", twitchLogin: "fekferk", twitchUrl: "https://www.twitch.tv/fekferk", displayName: "Fekferk_hoshino" },
  { discordUsername: "GoldOwlTV", twitchLogin: "goldowltv", twitchUrl: "https://www.twitch.tv/goldowltv", displayName: "GoldOwlTV" },
  { discordUsername: "jawade_lts12_ttv", twitchLogin: "jawade_lts12_ttv", twitchUrl: "https://www.twitch.tv/jawade_lts12_ttv", displayName: "jawade_lts12_ttv" },
  { discordUsername: "Elixon7", twitchLogin: "elixon7", twitchUrl: "https://www.twitch.tv/elixon7", displayName: "Elixon7" },
  { discordUsername: "Gabdeade", twitchLogin: "gabdeade", twitchUrl: "https://www.twitch.tv/gabdeade", displayName: "Gabdeade" },
  { discordUsername: "Papy Ragnar 🩵", twitchLogin: "papyragnar67", twitchUrl: "https://twitch.tv/papyragnar67", displayName: "Papy_Ragnar" },
  { discordUsername: "ChezVico", twitchLogin: "chezvico", twitchUrl: "https://www.twitch.tv/chezvico", displayName: "ChezVico" },
  { discordUsername: "Axplay_", twitchLogin: "axplay_", twitchUrl: "https://twitch.tv/axplay_", displayName: "Axplay_" },
  { discordUsername: "GlouBeer", twitchLogin: "gloubeer", twitchUrl: "https://www.twitch.tv/gloubeer", displayName: "GlouBeer" },
  { discordUsername: "JoCrm24", twitchLogin: "jocrm24", twitchUrl: "https://www.twitch.tv/jocrm24", displayName: "JoCrm24" },
];

// Fonction utilitaire pour obtenir un membre par son login Twitch
export function getMemberByTwitchLogin(login: string): Member | undefined {
  return allMembers.find((member) => member.twitchLogin.toLowerCase() === login.toLowerCase());
}

// Fonction utilitaire pour obtenir un membre par son pseudo Discord
export function getMemberByDiscordUsername(username: string): Member | undefined {
  return allMembers.find((member) => member.discordUsername.toLowerCase() === username.toLowerCase());
}

