import type { Discours2Part } from "./content";

export type { Discours2Part } from "./content";

/** Contenus issus du document « reunion » (mai 2026) — 9 blocs oraux. */
export const discours2General = {
  title: "Discours onboarding — mai 2026",
  subtitle: "Neuf blocs / pages (document reunion.docx) — points clés & conseils staff",
  points: [
    "1) Accueil & mise à l’aise : présence = bon état d’esprit, pas de pression.",
    "2) C’est quoi TENF : entraide réelle, humain avant stats, Discord + site.",
    "3) Entraide dans les deux sens : visibilité qui se construit, pas qui s’achète.",
    "4) Concrètement : vie quotidienne, Spotlight, raids internes + ouverture extérieure.",
    "5) Site TENF : partie publique + espace membre (démo live).",
    "6) Staff & rôles : accessibilité, équité ; Communauté ≠ sanction ; mineurs protégés.",
    "7) Écosystème : événements, collabs, progression, confidentialité des moments internes.",
    "8) Bien commencer : follow, raids, attitude ; points (reconnaissance, pas compétition) ; espace membre.",
    "9) Clôture : questions, intégration en cours pendant l’échange, bienvenue officielle.",
  ],
  conseils: [
    "Respecter l’ordre des blocs : chaque partie prépare la suivante.",
    "Bloc 5 : prévoir la démo site en direct ; les lignes entre parenthèses sont des repères pour le présentateur.",
    "Bloc 4 : la phrase d’ouverture peut être adaptée si besoin (voir discours).",
    "Garder des pauses après les phrases avec 👉 — ce sont des appuis oraux.",
    "Temps de questions : bloc 9, après l’annonce explicite.",
  ],
  phraseCentrale:
    "La New Family, c’est une communauté d’entraide où l’humain passe avant tout : on construit ensemble, avec un équilibre entre soutien reçu et soutien donné.",
  note:
    "Fondateurs : Clara, Nexou et Red — formulation neutre pour tout présentateur staff.",
};

export const discours2Parts: Discours2Part[] = [
  {
    slug: "accueil-mise-a-l-aise",
    title: "Accueil & mise à l’aise (version orale)",
    emoji: "👋",
    objectif: "Accueillir, rassurer et poser le cadre humain avant le fond.",
    points: [
      "Valoriser la présence à la réunion comme signal positif.",
      "« Ici vous avez votre place », tous niveaux.",
      "Pas de jugement ni de pression ; objectif : comprendre et s’intégrer à son rythme.",
      "Questions possibles pendant ou en fin de bloc.",
    ],
    conseils: [
      "Ton chaleureux, débit calme.",
      "Ne pas anticiper TENF / site / Spotlight dans ce bloc.",
    ],
    discours: [
      "Salut tout le monde 👋",
      "Déjà, merci d’être là aujourd’hui.",
      "Le simple fait que vous soyez présents à cette réunion, ça montre déjà quelque chose d’important : 👉 vous avez envie de comprendre, de vous intégrer et de faire partie de la communauté.",
      "Et ça, c’est exactement l’état d’esprit qu’on recherche ici 💜",
      "Alors avant de commencer, on veut vous dire une chose simple :",
      "👉 ici, vous avez votre place.",
      "Peu importe votre niveau, peu importe où vous en êtes dans votre parcours, que vous soyez débutant ou déjà expérimenté…",
      "la New Family est faite pour avancer ensemble, pas pour comparer.",
      "On n’est pas là pour juger, on n’est pas là pour mettre la pression,",
      "on est là pour créer quelque chose de collectif et de sain.",
      "Et cette réunion, elle est justement là pour vous aider à comprendre comment tout ça fonctionne, et surtout comment vous pouvez vous intégrer naturellement, à votre rythme.",
      "Donc vraiment, mettez-vous à l’aise, vous pouvez écouter tranquillement, poser vos questions à la fin, ou même pendant si besoin.",
      "💬 Le but, c’est que ce moment soit simple, clair… et humain.",
      "Encore bienvenue dans la New Family 💜",
    ],
    keywords: ["bienvenue", "humain"],
    phrasesCles: [
      "vous avez envie de comprendre, de vous intégrer et de faire partie de la communauté",
      "l'état d'esprit qu'on recherche ici",
      "vous avez votre place",
      "la New Family est faite pour avancer ensemble, pas pour comparer",
      "collectif et de sain",
      "à votre rythme",
      "simple, clair… et humain",
    ],
  },
  {
    slug: "cest-quoi-tenf",
    title: "C’est quoi TENF (version orale fluide)",
    emoji: "🌍",
    objectif: "Définir la New Family : entraide, collectif, humain avant les stats ; annoncer le site.",
    points: [
      "Ce n’est pas « un Discord parmi d’autres » : communauté d’entraide sur la durée.",
      "Pas compétition ni « chacun pour soi » ; logique collective.",
      "Humain avant chiffres, stats, performance.",
      "Discord + site pour structurer et centraliser.",
    ],
    conseils: [
      "Annoncer la démo site « juste après » sans tout montrer ici.",
      "Insister sur « construire ensemble » vs « être vu ».",
    ],
    discours: [
      "Maintenant que vous êtes là, on va répondre à une question simple :",
      "👉 c’est quoi exactement la New Family ?",
      "Parce qu’au premier regard, ça peut ressembler à un Discord de streamers…",
      "mais en réalité, c’est très différent.",
      "Ici, vous n’avez pas rejoint un serveur parmi tant d’autres.",
      "👉 La New Family, c’est une communauté d’entraide.",
      "Une communauté où des streamers, des créateurs et des passionnés avancent ensemble, se soutiennent vraiment, et construisent quelque chose sur la durée.",
      "On n’est pas dans une logique de compétition, on n’est pas dans une logique de “chacun pour soi”.",
      "👉 On est dans une logique collective.",
      "Et il y a une chose très importante à comprendre :",
      "ici, l’humain passe avant tout.",
      "Avant les chiffres, avant les stats, avant la performance.",
      "Ce qui compte, c’est les échanges, les liens que vous allez créer, et la manière dont vous allez vous intégrer dans la communauté.",
      "Et aujourd’hui, pour que tout ça fonctionne de manière claire et structurée, 👉 on ne s’appuie pas uniquement sur Discord.",
      "On a aussi mis en place un site qui centralise toute la communauté, que ce soit les membres, les événements ou votre évolution dans TENF.",
      "On y reviendra juste après pour vous montrer concrètement comment ça fonctionne 👀",
      "Mais ce qu’il faut retenir ici, c’est simple :",
      "👉 la New Family, ce n’est pas un endroit où on vient juste pour être vu.",
      "👉 c’est un endroit où on vient pour construire, ensemble.",
    ],
    keywords: ["entraide", "site"],
    phrasesCles: [
      "c'est quoi exactement la New Family ?",
      "La New Family, c'est une communauté d'entraide",
      "logique collective",
      "l'humain passe avant tout",
      "on ne s'appuie pas uniquement sur Discord",
      "un site qui centralise toute la communauté",
      "juste pour être vu",
      "construire, ensemble",
    ],
  },
  {
    slug: "entraide-deux-sens",
    title: "L’entraide fonctionne dans les deux sens (version orale)",
    emoji: "⚖️",
    objectif: "Expliquer réciprocité, visibilité qui se construit, cohérence sans perfectionnisme.",
    points: [
      "Visibilité et soutien ne tombent pas du ciel ; ne s’achètent pas.",
      "Implication, présence, participation.",
      "Pas des consommateurs de visibilité : des personnes qui s’intègrent et construisent.",
      "Pas besoin d’être parfait : régularité naturelle.",
    ],
    conseils: [
      "Marteler l’équilibre donné / reçu sans culpabiliser.",
      "Éviter les promesses de résultats chiffrés.",
    ],
    discours: [
      "Maintenant que vous avez compris ce qu’est la New Family, il y a une chose essentielle à comprendre pour que tout fonctionne correctement ici.",
      "👉 L’entraide fonctionne dans les deux sens.",
      "Ça veut dire quoi concrètement ?",
      "Ça veut dire que la visibilité, le soutien, la présence… 👉 ça ne tombe pas du hasard.",
      "Et surtout, ça ne s’achète pas.",
      "Ici, on n’est pas dans un système où vous arrivez et où vous êtes automatiquement mis en avant.",
      "👉 La visibilité se construit.",
      "Elle se construit avec :",
      "• votre implication • votre présence • votre participation dans la communauté",
      "Et c’est justement ça qui fait la force de la New Family.",
      "Parce que chacun contribue à faire vivre le système.",
      "👉 On ne vient pas seulement pour être soutenu. 👉 On vient aussi pour soutenir les autres.",
      "Et c’est important de le dire clairement dès le début :",
      "ici, on ne cherche pas des personnes qui viennent consommer de la visibilité,",
      "👉 on cherche des personnes qui veulent s’intégrer et construire avec les autres.",
      "Mais attention, ça ne veut pas dire être partout, tout le temps.",
      "👉 On ne vous demande pas d’être parfaits.",
      "On vous demande simplement d’être cohérents :",
      "• passer quand vous pouvez • soutenir quand vous êtes disponibles • participer naturellement",
      "Et plus vous allez vous impliquer, 👉 plus la communauté va naturellement s’impliquer pour vous.",
      "C’est un équilibre.",
      "Et c’est cet équilibre qui permet à tout le monde d’avancer ensemble, sans pression inutile.",
    ],
    keywords: ["visibilité", "équilibre"],
    phrasesCles: [
      "L'entraide fonctionne dans les deux sens",
      "ça ne tombe pas du hasard",
      "ça ne s'achète pas",
      "La visibilité se construit",
      "On ne vient pas seulement pour être soutenu",
      "On vient aussi pour soutenir les autres",
      "consommer de la visibilité",
      "On ne vous demande pas d'être parfaits",
      "être cohérents",
      "sans pression inutile",
    ],
  },
  {
    slug: "spotlight-raids-ouverts",
    title: "Spotlight + raids ouverts (version orale)",
    emoji: "🌟",
    objectif: "Quotidien de l’entraide, Spotlight, raids internes et ouverture extérieure.",
    points: [
      "Petits gestes répétés : lives, chat, vocaux.",
      "Spotlight ≈ 1 h, lien et place dans la communauté.",
      "Présence régulière sur les Spotlights des autres.",
      "Raids internes + raids externes ; pas une bulle fermée.",
    ],
    conseils: [
      "Phrase d’accroche du bloc : voir première ligne du discours — peut être adaptée au présentateur.",
      "Phrase clé : « point d’ancrage, pas une cage ».",
    ],
    discours: [
      "Passons à ce qui se passe au quotidien 👇",
      "Maintenant que vous avez compris le principe d’entraide et de réciprocité, on va voir quelque chose de très important :",
      "👉 comment ça se passe concrètement dans la New Family.",
      "Parce que l’entraide ici, ce n’est pas juste un mot.",
      "👉 C’est quelque chose qui se vit au quotidien.",
      "Ça passe par des choses simples :",
      "• passer sur les lives des autres • échanger dans le chat • participer aux vocaux • prendre quelques minutes pour soutenir quelqu’un",
      "Ce sont des petits gestes… 👉 mais répétés régulièrement, ils font toute la différence.",
      "Et pour structurer tout ça, on a mis en place plusieurs moments clés dans la communauté.",
      "Le plus important, c’est le Spotlight.",
      "👉 Le Spotlight, c’est un moment où la communauté se rassemble autour d’un streamer pendant environ une heure.",
      "Le but, ce n’est pas juste de ramener du monde d’un coup.",
      "👉 C’est de créer du lien, de faire découvrir un univers, et de renforcer la place de chacun dans la communauté.",
      "Mais il y a un point très important à comprendre :",
      "👉 le Spotlight ne fonctionne que si tout le monde joue le jeu.",
      "Être membre actif ici, ce n’est pas seulement attendre son tour.",
      "👉 c’est aussi être présent sur les Spotlights des autres quand vous êtes disponibles.",
      "Pas à chaque fois, pas par obligation,",
      "👉 mais de manière régulière.",
      "Parce que c’est ça qui crée la dynamique.",
      "👉 Quand vous soutenez les autres, la communauté sera naturellement là pour vous aussi.",
      "À côté de ça, il y a aussi les raids.",
      "👉 Les raids internes sont un pilier important de l’entraide ici.",
      "Ils permettent de :",
      "• soutenir les membres de la communauté • créer du lien entre vous • renforcer la dynamique collective",
      "Mais il y a quelque chose de très important à comprendre :",
      "👉 la New Family n’est pas une bulle fermée.",
      "👉 Vous pouvez — et même vous devez — aussi raider en dehors.",
      "Parce que c’est ça qui permet :",
      "• d’élargir votre réseau • de faire découvrir la communauté à d’autres • de garder une dynamique naturelle",
      "👉 La New Family est un point d’ancrage, pas une cage.",
      "Et c’est cet équilibre entre entraide interne et ouverture extérieure 👉 qui permet à chacun de vraiment évoluer.",
    ],
    keywords: ["Spotlight", "raids"],
    phrasesCles: [
      "comment ça se passe concrètement dans la New Family",
      "se vit au quotidien",
      "Le Spotlight, c'est un moment où la communauté se rassemble autour d'un streamer pendant environ une heure",
      "le Spotlight ne fonctionne que si tout le monde joue le jeu",
      "Les raids internes sont un pilier important de l'entraide ici",
      "la New Family n'est pas une bulle fermée",
      "La New Family est un point d'ancrage, pas une cage",
      "entraide interne et ouverture extérieure",
    ],
  },
  {
    slug: "site-tenf-demo",
    title: "Le site TENF (version orale + démo)",
    emoji: "💻",
    objectif: "Cadre de la démo : public vs espace membre, pas tout maîtriser le jour J.",
    points: [
      "Centralise membres, lives, événements, Spotlights (public).",
      "Espace membre : profil, planning, activité, raids, progression.",
      "Pas tout comprendre tout de suite ; usage progressif.",
    ],
    conseils: [
      "(👉 À ce stade : ouvrir et montrer le site) — préparer les onglets à l’avance.",
      "Les indications entre parenthèses sont pour le présentateur : pas à lire mot pour mot si vous naviguez déjà.",
    ],
    discours: [
      "Maintenant, nous allons vous montrer quelque chose de très important.",
      "👉 Parce que tout ce qu’on vient de voir, ce n’est pas juste des mots.",
      "Pour que la communauté soit claire, structurée et accessible à tous, 👉 on a créé un site qui centralise toute la New Family.",
      "Et c’est vraiment important pour vous, parce que c’est un outil que vous allez utiliser régulièrement.",
      "(👉 À ce stade : ouvrir et montrer le site)",
      "👉 Ici, vous avez toute la partie publique.",
      "Par exemple :",
      "• l’annuaire des membres • les lives en cours • les événements et les Spotlights",
      "👉 Ça permet à n’importe qui de découvrir la communauté et les créateurs.",
      "(montrer rapidement les pages)",
      "Mais surtout, 👉 une fois que vous êtes intégrés, vous avez accès à votre espace membre.",
      "(montrer / expliquer sans forcément tout ouvrir — fonctionnement TENF, système de points)",
      "Et là, ça devient votre outil personnel dans la New Family :",
      "• votre profil • votre planning • votre suivi d’activité • vos raids • votre progression",
      "👉 Tout ce que vous faites dans la communauté peut être suivi et valorisé ici.",
      "Et ça, c’est important, parce que votre implication ne reste pas invisible.",
      "👉 Elle est reconnue, structurée et utilisée pour vous faire évoluer.",
      "Le site sert aussi à organiser toute la vie de la communauté :",
      "• les événements • les Spotlights • les ressources",
      "👉 En résumé, c’est un peu le centre de contrôle de la New Family.",
      "Mais ne vous inquiétez pas, 👉 vous n’avez pas besoin de tout comprendre aujourd’hui.",
      "Le but, c’est simplement que vous sachiez qu’il existe, et que vous allez vous en servir progressivement.",
      "Et surtout :",
      "👉 il est là pour vous aider à ne pas être perdus, et pour vous guider dans votre évolution dans la communauté.",
    ],
    keywords: ["progression"],
    phrasesCles: [
      "un site qui centralise toute la New Family",
      "votre espace membre",
      "votre outil personnel dans la New Family",
      "centre de contrôle de la New Family",
      "vous n'avez pas besoin de tout comprendre aujourd'hui",
      "partie publique",
      "reconnue, structurée et utilisée pour vous faire évoluer",
    ],
  },
  {
    slug: "organisation-roles",
    title: "Organisation & rôles (version orale fluide)",
    emoji: "🧑‍🤝‍🧑",
    objectif: "Staff humain et accessible ; rôles pour organiser ; Communauté ; mineurs.",
    points: [
      "Fondateurs, coordinateurs, modération ; règles pour tous y compris staff.",
      "Rôles ne valent pas jugement ; évolution avec l’implication.",
      "Communauté : pas une sanction ; retour actif possible.",
      "Rôles jeunes : cadre adapté, pas exclusion.",
    ],
    conseils: [
      "Les trois fondateurs nommés sont Clara, Nexou et Red — ajuster seulement si le wording staff change.",
      "Temps sur « Communauté » pour lever les peurs.",
    ],
    discours: [
      "Derrière la New Family, il y a quelque chose d’important à comprendre :",
      "👉 ce ne sont pas juste des rôles ou des couleurs Discord.",
      "👉 Ce sont des personnes.",
      "Des personnes qui donnent de leur temps, de leur énergie, pour faire vivre la communauté au quotidien.",
      "À la base du projet, il y a les fondateurs : Clara, Nexou et Red.",
      "👉 Leur rôle, ce n’est pas seulement de gérer.",
      "C’est surtout :",
      "• d’organiser • d’accompagner • d’écouter • et de maintenir un cadre juste pour tout le monde",
      "À côté de ça, il y a aussi les Admin Coordinateurs.",
      "👉 Leur rôle, c’est d’assurer que tout fonctionne bien au quotidien, de faire le lien entre le staff et de garder une bonne organisation globale.",
      "Et ensuite, il y a les modérateurs.",
      "👉 Ils sont là pour :",
      "• accompagner les membres • faire respecter le cadre • et maintenir une ambiance saine",
      "Et c’est important de le dire :",
      "👉 toute l’équipe est formée 👉 et les règles s’appliquent à tout le monde, y compris au staff",
      "Parce que la cohérence et l’équité sont essentielles ici.",
      "Et surtout :",
      "👉 le staff reste accessible.",
      "Vous pouvez venir parler au staff, poser vos questions, demander de l’aide.",
      "Il n’y a pas de barrière volontaire,",
      "👉 juste un cadre pour que tout le monde puisse évoluer sereinement.",
      "Et de votre côté, vous avez aussi des rôles,",
      "mais il y a une chose très importante à comprendre :",
      "👉 les rôles ici ne servent pas à juger ou à classer les gens.",
      "👉 Ils servent à organiser la communauté.",
      "Et surtout, ils évoluent avec votre implication.",
      "Rien n’est figé.",
      "👉 Vous avancez à votre rythme, et votre place évolue naturellement avec vous dans la New Family.",
      "Il y a notamment un rôle qu’il est important de bien comprendre :",
      "👉 le rôle Communauté.",
      "Ce rôle regroupe plusieurs situations :",
      "• des viewers engagés • des streamers en pause • ou des personnes dont l’implication est plus faible sur une période",
      "Et c’est important de le dire clairement :",
      "👉 ce rôle n’est pas une sanction.",
      "👉 Il reflète simplement le niveau d’implication du moment.",
      "La seule différence, c’est que la mise en avant est moins active.",
      "Mais vous gardez accès à la communauté, vous pouvez continuer à échanger, participer…",
      "👉 et surtout, revenir à un rôle actif à tout moment.",
      "Il suffit simplement de reprendre une implication naturelle.",
      "Et ça, c’est important, parce que chacun peut avoir des périodes plus calmes.",
      "👉 La New Family s’adapte à vous, elle ne vous exclut pas.",
      "On a aussi des rôles spécifiques pour protéger les plus jeunes.",
      "👉 Les créateurs mineurs 👉 et les viewers mineurs",
      "L’objectif, ce n’est pas de les limiter,",
      "👉 mais de garantir un cadre adapté, sain et sécurisé.",
      "Encore une fois, 👉 tout est pensé pour que chacun puisse évoluer dans de bonnes conditions.",
    ],
    keywords: ["staff", "mineurs"],
    phrasesCles: [
      "ce ne sont pas juste des rôles ou des couleurs Discord",
      "Ce sont des personnes",
      "Clara, Nexou et Red",
      "les règles s'appliquent à tout le monde, y compris au staff",
      "ce rôle n'est pas une sanction",
      "Il reflète simplement le niveau d'implication du moment",
      "La New Family s'adapte à vous, elle ne vous exclut pas",
      "le rôle Communauté",
      "cadre adapté, sain et sécurisé",
    ],
  },
  {
    slug: "ecosysteme-tenf",
    title: "L’écosystème TENF (version orale fluide)",
    emoji: "🚀",
    objectif: "Événements, collabs, progression, IRL ; confidentialité des moments internes.",
    points: [
      "Écosystème = Discord + vie communautaire + projets.",
      "Événements facultatifs mais créateurs de lien.",
      "Formations & ressources pour un projet durable.",
      "Confiance : ce qui est interne ne part pas en live sans cadre.",
    ],
    conseils: [
      "Exemples IRL au présent si vous en avez (sinon rester général).",
      "Ton ferme mais calme sur la confidentialité.",
    ],
    discours: [
      "La New Family, ce n’est pas seulement un serveur Discord, et ce n’est pas seulement un système d’entraide.",
      "👉 C’est un véritable écosystème.",
      "Une communauté qui vit au quotidien, à travers des moments, des projets et des échanges.",
      "Concrètement, ça passe par plusieurs choses.",
      "Il y a d’abord les événements communautaires.",
      "👉 Des soirées gaming, 👉 des moments plus chill, 👉 des activités organisées entre membres",
      "Rien n’est obligatoire,",
      "👉 mais ces moments permettent de créer du lien autrement que sur les lives.",
      "Et c’est souvent là que la communauté devient vraiment… une communauté.",
      "Il y a aussi tout ce qui est collaboration.",
      "👉 Des projets entre streamers 👉 des idées qui naissent directement de la communauté 👉 des événements créés ensemble",
      "Ici, on encourage les initiatives.",
      "👉 Vous n’êtes pas juste “membres”, 👉 vous pouvez aussi devenir acteurs de la dynamique.",
      "À côté de ça, il y a aussi tout l’aspect progression.",
      "👉 Des formations 👉 des ressources 👉 des conseils",
      "L’objectif, ce n’est pas seulement de vous faire gagner en visibilité,",
      "👉 c’est de vous aider à construire un projet de streaming plus solide et plus durable.",
      "Et parfois, 👉 ça va même au-delà du virtuel.",
      "Il y a des projets IRL, des rencontres, des événements qui permettent de créer des liens encore plus forts.",
      "Tout ça repose sur une chose simple :",
      "👉 l’entraide ne s’arrête pas à un live.",
      "Elle se vit dans les échanges, dans les projets, et dans les moments partagés.",
      "Et c’est aussi pour ça qu’on tient à un point important :",
      "👉 tout ce qui se passe dans ces moments communautaires reste dans la communauté.",
      "Les vocaux, les soirées, les échanges… 👉 ne sont pas faits pour être diffusés en live.",
      "Ça permet de garder un espace sain, où chacun peut être à l’aise.",
      "👉 La confiance, ici, est essentielle.",
    ],
    keywords: ["écosystème"],
    phrasesCles: [
      "C'est un véritable écosystème",
      "l'entraide ne s'arrête pas à un live",
      "reste dans la communauté",
      "ne sont pas faits pour être diffusés en live",
      "La confiance, ici, est essentielle",
      "devenir acteurs de la dynamique",
      "projet de streaming plus solide et plus durable",
    ],
  },
  {
    slug: "comment-bien-commencer",
    title: "Comment bien commencer (version orale fluide)",
    emoji: "📈",
    objectif:
      "Follow, raids, attitude ; système de points comme reconnaissance (pas compétition) ; espace membre ; solliciter le staff et les membres.",
    points: [
      "Découvrir les autres : follow comme ouverture, pas échange auto.",
      "Raids TENF + ouverture extérieure.",
      "Respect, présence simple, régulière.",
      "Points : visibilité de l’engagement, accès à certains moments (Spotlights, etc.), sans obligation de performance.",
      "Site pour progression et organisation.",
    ],
    conseils: [
      "Répéter « point d’ancrage, pas une cage » si pas déjà saturé au bloc 4.",
      "Inviter à l’écrit ou au vocal après la réunion.",
    ],
    discours: [
      "Maintenant que vous avez compris comment fonctionne la New Family, la question la plus importante, c’est :",
      "👉 comment bien commencer ?",
      "Et en réalité, il n’y a rien de compliqué.",
      "👉 Tout commence par une chose simple : découvrir les autres.",
      "Concrètement, ça passe par un premier geste :",
      "👉 suivre les chaînes des membres actifs.",
      "Mais attention, ici le follow n’est pas un échange automatique.",
      "👉 C’est un point de départ.",
      "Ça vous permet :",
      "• de repérer les créateurs • de découvrir leurs univers • et de créer des liens progressivement",
      "On ne vous demande pas d’aimer tout le monde,",
      "👉 on vous demande simplement d’ouvrir la porte.",
      "Ensuite, il y a les raids.",
      "👉 Raidez la New Family quand c’est possible,",
      "mais gardez aussi une ouverture vers l’extérieur.",
      "👉 Encore une fois, la New Family est un point d’ancrage, pas une cage.",
      "Et au-delà du follow et des raids,",
      "👉 ce qui compte vraiment, c’est votre attitude.",
      "• être respectueux • être présent quand vous pouvez • échanger naturellement",
      "Pas besoin d’en faire trop.",
      "👉 Une présence simple et régulière fait déjà toute la différence.",
      "Et pour accompagner tout ça,",
      "👉 on a mis en place un système de points.",
      "Mais il y a une chose importante à comprendre :",
      "👉 ce n’est pas un système de compétition.",
      "👉 ce n’est pas un classement.",
      "C’est simplement une manière de reconnaître votre implication dans la communauté.",
      "Les points se gagnent naturellement,",
      "👉 en faisant ce que l’entraide encourage déjà :",
      "• participer aux événements",
      "• passer sur les lives",
      "• faire des raids",
      "• échanger avec les autres",
      "👉 Rien de plus.",
      "Et ces points vous permettent ensuite d’accéder à certaines choses,",
      "comme par exemple :",
      "• des Spotlights",
      "• des mises en avant",
      "• ou d’autres éléments liés à la communauté",
      "👉 L’idée, c’est simplement de rendre visible votre engagement.",
      "Et surtout,",
      "👉 vous avancez à votre rythme.",
      "Il n’y a aucune obligation de performance.",
      "👉 chaque action compte, même les plus simples.",
      "Et pour vous aider, 👉 vous aurez accès à votre espace membre sur le site,",
      "qui vous permettra de :",
      "• suivre votre progression • participer aux événements • vous organiser plus facilement",
      "Et surtout,",
      "👉 n’hésitez pas à venir parler.",
      "Que ce soit avec les membres ou avec le staff,",
      "👉 vous n’êtes pas seuls ici.",
      "Prenez le temps, avancez à votre rythme,",
      "👉 et laissez les choses se construire naturellement.",
    ],
    keywords: ["follow", "points"],
    phrasesCles: [
      "comment bien commencer",
      "le follow n'est pas un échange automatique",
      "point d'ancrage, pas une cage",
      "vous n'êtes pas seuls ici",
      "ce qui compte vraiment, c'est votre attitude",
      "Une présence simple et régulière fait déjà toute la différence",
      "un système de points",
      "ce n'est pas un système de compétition",
      "ce n'est pas un classement",
      "reconnaître votre implication dans la communauté",
      "Les points se gagnent naturellement",
      "rendre visible votre engagement",
      "aucune obligation de performance",
      "chaque action compte, même les plus simples",
      "votre espace membre sur le site",
    ],
  },
  {
    slug: "conclusion-integration-directe",
    title: "Conclusion — intégration en direct (version orale)",
    emoji: "🏁",
    objectif: "Questions, annoncer l’intégration en cours, message final humain et bienvenue.",
    points: [
      "Temps de questions après l’invitation explicite.",
      "Rôle actif / chaîne : en cours pendant la fin de réunion.",
      "Pas tout faire immédiatement ; chaque action compte.",
      "Cohérence + humain.",
    ],
    conseils: [
      "Laisser le temps d’échange annoncé dans le doc.",
      "Clôturer sur un ton chaleureux.",
    ],
    discours: [
      "Et voilà, on arrive à la fin de cette réunion d’intégration.",
      "Déjà, merci à vous d’avoir été présents, d’avoir pris le temps d’écouter et de vous intéresser au fonctionnement de la New Family.",
      "👉 Le simple fait d’être là aujourd’hui montre déjà votre envie de vous intégrer, et c’est quelque chose qu’on valorise énormément.",
      "Avant de conclure, 👉 on va prendre quelques minutes si vous avez des questions.",
      "Que ce soit sur le fonctionnement, le site, les Spotlights, ou quoi que ce soit d’autre…",
      "👉 n’hésitez pas, c’est le moment.",
      "(laisser un temps d’échange)",
      "Et pendant qu’on discute, 👉 vous êtes déjà en train d’être intégrés dans le système.",
      "Votre rôle actif est en cours d’attribution, votre chaîne est en train d’être ajoutée,",
      "👉 et vous entrez concrètement dans la dynamique de la New Family.",
      "Donc à la fin de cette réunion, 👉 vous êtes déjà dedans.",
      "À partir de maintenant, vous avez toutes les clés.",
      "Prenez le temps d’explorer, de découvrir les autres, de passer sur les lives quand vous êtes disponibles, et de participer à votre rythme.",
      "👉 Rien n’est obligatoire immédiatement, mais chaque action compte.",
      "Et surtout, gardez une chose en tête :",
      "👉 la New Family fonctionne sur la cohérence et l’humain.",
      "Plus vous serez dans cette logique, 👉 plus vous trouverez naturellement votre place ici.",
      "Encore une fois,",
      "👉 bienvenue dans la New Family 💜",
      "On est sincèrement contents de vous compter parmi nous.",
    ],
    keywords: ["questions"],
    phrasesCles: [
      "vous êtes déjà en train d'être intégrés dans le système",
      "vous êtes déjà dedans",
      "la New Family fonctionne sur la cohérence et l'humain",
      "bienvenue dans la New Family",
      "chaque action compte",
      "n'hésitez pas, c'est le moment",
    ],
  },
];
