export type Discours2Part = {
  slug: string;
  title: string;
  emoji: string;
  objectif: string;
  points: string[];
  conseils: string[];
  discours: string[];
  keywords: string[];
};

export const discours2General = {
  title: "Parcours Discours 2",
  subtitle: "Accueil global de la présentation d'intégration",
  points: [
    "1) Expliquer l'esprit de la New Family: communaute d'entraide reelle, basee sur l'humain, la bienveillance et la progression collective; la visibilite ne s'achete pas, elle se construit par l'implication.",
    "2) Montrer que la communaute est structuree: presenter l'histoire, les valeurs, le staff et les roles; expliquer que le cadre protege la communaute.",
    "3) Expliquer comment fonctionne l'entraide: Spotlights, raids, participation aux lives, echanges sur Discord. Idee centrale: on recoit du soutien mais on en donne aussi.",
    "4) Presenter les outils de progression: points et boutique, evenements, formations, site web et ressources. Objectif: montrer que la communaute aide reellement a progresser.",
    "5) Clarifier l'engagement attendu: decouvrir les autres streamers, participer quand on peut, respecter le cadre, contribuer a la dynamique collective. Sans pression, mais avec coherence.",
    "6) Rassurer les nouveaux: chacun avance a son rythme, rien n'est fige, l'integration se fait progressivement.",
  ],
  conseils: [
    "1. Parler avec chaleur et naturel: la reunion doit ressembler a une invitation dans une communaute, pas a une presentation administrative.",
    "2. Garder le fil conducteur: toujours revenir au message central -> entraide, collectif, implication humaine.",
    "3. Expliquer le cadre sans rigidite: il sert a proteger la communaute, maintenir l'equite et garder un environnement sain.",
    "4. Valoriser les membres: chacun a sa place, chaque participation compte, la communaute existe grace aux membres.",
    "5. Mettre l'accent sur les opportunites: Spotlight, evenements, collaborations, comme des opportunites et non des obligations.",
    "6. Garder un rythme fluide: eviter les passages trop techniques, faire des transitions simples, prendre des temps de questions.",
  ],
  phraseCentrale:
    "La New Family est une communaute structuree d'entraide entre streamers ou chacun peut progresser, a condition de participer a la dynamique collective.",
  note:
    "Ton document est tres solide pour une reunion d'integration: il combine bien valeurs humaines, structure et outils.",
};

export const discours2Parts: Discours2Part[] = [
  {
    slug: "intro",
    title: "Introduction",
    emoji: "👋",
    objectif: "Accueillir et poser le cadre humain de la New Family.",
    points: [
      "Souhaiter la bienvenue et valoriser la présence des participants.",
      "Présenter la New Family comme une communauté structurée et humaine.",
      "Expliquer la réciprocité: on reçoit du soutien et on en donne.",
      "Rassurer: chacun avance à son rythme, sans pression.",
    ],
    conseils: [
      "Parler avec chaleur et sourire dans la voix.",
      "Insister sur les notions de collectif et d'implication.",
      "Reformuler le message central avant la transition.",
    ],
    discours: [
      "Salut tout le monde, et bienvenue officiellement dans la Twitch Entraide New Family !",
      "Merci d'avoir pris le temps d'etre ici aujourd'hui. Le simple fait de rejoindre cette reunion montre deja une chose essentielle : vous avez envie de comprendre, de vous integrer et de faire partie d'un collectif.",
      "Ici, vous n'avez pas rejoint un Discord parmi tant d'autres. La New Family, c'est une famille choisie : une communaute de streamers, de createurs et de passionnes qui avancent ensemble, qui s'entraident reellement et qui construisent quelque chose sur la duree.",
      "Vous avez tous votre place ici.",
      "Mais notre fonctionnement repose sur un principe simple : l'entraide fonctionne dans les deux sens.",
      "La visibilite ne s'achete pas, elle ne se donne pas au hasard - elle se construit par l'implication, le respect et la participation a la vie collective.",
      "Cette reunion n'a pas pour but de vous noyer sous des regles, mais de vous expliquer pourquoi nous avons un cadre, comment il protege la communaute, et comment il peut vous aider a evoluer dans votre streaming et humainement.",
      "Ici, l'entraide n'est pas un mot dans un titre.",
      "C'est une dynamique quotidienne : dans les lives, sur Discord, dans les vocaux, dans les formations et dans les moments plus legers.",
      "Vous avancez a votre rythme.",
      "Mais si vous choisissez de vous engager, la communaute s'engagera pour vous.",
      "Encore bienvenue dans la New Family 💜",
      "On va maintenant voir ensemble comment tout cela fonctionne concretement.",
    ],
    keywords: ["bienvenue", "collectif", "entraide", "implication", "respect", "rythme"],
  },
  {
    slug: "histoire",
    title: "Histoire et fondations",
    emoji: "📜",
    objectif: "Montrer l'origine du projet et ses valeurs non negociables.",
    points: [
      "Raconter la transition de Twitch Entraide Family vers New Family.",
      "Expliquer la ligne rouge: refus de monnayer l'entraide.",
      "Rappeler la date cle du 2 septembre 2024.",
      "Souligner la croissance et la diversite de la communaute.",
    ],
    conseils: [
      "Raconter cette partie comme une histoire vraie, pas comme une liste.",
      "Mettre fortement en avant les valeurs fondatrices.",
      "Conclure sur \"l'humain avant tout\".",
    ],
    discours: [
      "Pour comprendre ce qu'est aujourd'hui la New Family, il faut revenir un peu en arriere.",
      "Avant d'etre ce que vous decouvrez maintenant, le serveur s'appelait Twitch Entraide Family. A l'origine, c'etait une idee simple nee entre passionnes : creer un espace d'entraide entre streamers, sans competition inutile ni pression.",
      "Tres vite, une equipe s'est formee. Des personnes ont donne de leur temps et de leur energie pour poser les premieres bases : des salons, des outils, des regles... mais surtout une ambiance humaine et bienveillante.",
      "Avec le temps, une divergence importante est apparue. Le point de rupture a ete le moment ou l'un des createurs a souhaite faire payer l'entree et/ou la visibilite.",
      "Pour nous, c'etait une ligne rouge.",
      "L'entraide ne se monetise pas ici.",
      "La visibilite ne s'achete pas.",
      "Nous avons donc choisi de rester fideles a nos valeurs - et les cles du projet nous ont ete confiees.",
      "C'est ainsi qu'est nee la Twitch Entraide New Family.",
      "Le 2 septembre 2024 marque notre veritable nouveau depart.",
      "Nous avons relance le serveur sur des bases plus claires, plus solides et plus coherentes : une entraide reelle, un cadre assume et une vision tournee vers la progression collective.",
      "A la relance, nous etions 42 membres.",
      "Aujourd'hui, la communaute compte plus de 560 membres, dont plus de 200 engages activement dans le systeme d'entraide.",
      "Mais au-dela des chiffres, notre richesse reste la diversite : des streamers debutants, des createurs experimentes, des viewers engages.",
      "La New Family n'est pas une course et n'est pas un classement.",
      "C'est une communaute structuree qui avance ensemble, apprend ensemble et protege un principe essentiel : l'humain avant tout.",
    ],
    keywords: ["valeurs", "ligne rouge", "2 septembre 2024", "coherent", "humain"],
  },
  {
    slug: "staff",
    title: "Le staff",
    emoji: "🛡️",
    objectif: "Presenter une equipe accessible, organisee et equitable.",
    points: [
      "Expliquer les roles: fondateurs, coordinateurs, moderation.",
      "Montrer que le staff sert, accompagne et structure la communaute.",
      "Rappeler l'accessibilite du staff en salon, vocal et message prive.",
      "Insister sur l'equite: les regles s'appliquent a tous.",
    ],
    conseils: [
      "Presenter les roles avec des exemples concrets de missions.",
      "Eviter le ton \"hierarchique\", privilegier l'idee de service.",
      "Conclure sur la coherence et la justice du cadre.",
    ],
    discours: [
      "Derriere la New Family, il y a avant tout des personnes.",
      "Pas simplement des roles ou des couleurs Discord, mais des humains qui donnent de leur temps et de leur energie pour faire vivre la communaute au quotidien.",
      "La New Family repose d'abord sur trois Admin Fondateurs : Clara, Nexou et Red.",
      "Ce sont eux qui portent le projet depuis le debut, qui en definissent la vision et qui veillent a ce que l'esprit New Family reste aligne avec ses valeurs.",
      "Leur role n'est pas seulement de decider, mais surtout d'ecouter, d'organiser, d'accompagner et de maintenir un cadre juste pour tous.",
      "Vous les croiserez regulierement : sur Discord, en vocal, dans les salons, en message prive, mais aussi dans les lives, les raids et les evenements communautaires.",
      "A leurs cotes, les Admin Coordinateurs assurent la coordination et la continuite du fonctionnement du serveur.",
      "Leur role est de faciliter l'organisation interne, d'assurer un lien fluide entre les moderateurs et les fondateurs, et d'aider a maintenir une bonne circulation de l'information au sein du staff.",
      "Ils participent egalement au suivi de certains projets ou initiatives communautaires.",
      "Aujourd'hui, ce role est assure notamment par Nangel et Tab's.",
      "Certaines personnes du staff peuvent aussi traverser des periodes ou leur disponibilite est plus limitee.",
      "C'est le cas actuellement de Selena_akemi et Jenny31200, qui sont temporairement en pause.",
      "La New Family reste avant tout un espace humain : il est normal que chacun puisse prendre du recul lorsque la vie personnelle ou professionnelle le demande.",
      "La moderation joue egalement un role essentiel dans la vie de la communaute.",
      "Les moderateurs sont formes pour :",
      "accompagner les membres",
      "faire respecter le cadre",
      "gerer les situations de moderation lorsque c'est necessaire",
      "et participer a maintenir une ambiance saine et respectueuse.",
      "Certains membres peuvent egalement rejoindre l'equipe a travers un role de Moderateur en formation, qui permet d'apprendre progressivement les outils et les situations liees a la moderation avant d'integrer pleinement l'equipe.",
      "Enfin, il existe aussi d'autres formes d'implication autour du staff, notamment avec le role Soutien TENF, qui permet a des membres investis ou a d'anciens membres du staff de continuer a contribuer a la vie de la communaute, tout en ayant un niveau d'implication plus souple.",
      "Une chose importante : le staff applique les regles a tous - y compris a lui-meme.",
      "La coherence et l'equite sont des principes essentiels ici.",
      "Et bien sur, le staff reste accessible.",
      "Vous pouvez nous parler en salon, en vocal ou en message prive.",
      "Il n'y a pas de barriere volontaire, mais il existe un cadre pour que chacun puisse evoluer dans un espace respectueux.",
      "Ensemble, fondateurs, coordinateurs et moderateurs forment une equipe engagee au service de la communaute.",
    ],
    keywords: ["staff", "accompagne", "equite", "accessible", "cadre juste"],
  },
  {
    slug: "roles",
    title: "Roles communautaires",
    emoji: "🏷️",
    objectif: "Faire comprendre les roles comme outil d'organisation, pas de jugement.",
    points: [
      "Les roles structurent la visibilite et le fonctionnement du serveur.",
      "Le role Communaute n'est pas une sanction.",
      "Le retour en role actif est possible par une reprise d'engagement.",
      "Des roles specifiques existent pour proteger les mineurs.",
    ],
    conseils: [
      "Dire explicitement qu'il n'y a pas de hierarchie de valeur humaine.",
      "Expliquer calmement la logique de visibilite.",
      "Rassurer sur la possibilite d'evolution des roles.",
    ],
    discours: [
      "Dans la New Family, nous avons mis en place des roles.",
      "Mais il y a une chose essentielle a comprendre : ici, chacun a sa place.",
      "Les roles ne servent pas a juger ou a hierarchiser les personnes.",
      "Ils servent a structurer le fonctionnement du serveur et a organiser la visibilite de maniere equitable.",
      "On distingue d'abord les createurs actifs.",
      "Les createurs affilies sont les streamers ayant obtenu le statut Twitch Affiliate.",
      "Les createurs en developpement sont ceux qui sont en cours de progression. Ici, ce terme n'est pas une comparaison, mais une etape.",
      "Les createurs en pause concernent les absences temporaires tout en restant engages dans la communaute.",
      "Il existe egalement le role Communaute, et il est important de bien le comprendre.",
      "Ce role regroupe :",
      "- les viewers engages",
      "- les streamers qui ne souhaitent pas de mise en avant",
      "- les createurs en pause longue",
      "- ou les membres dont l'implication dans l'entraide n'etait plus suffisante sur la periode observee.",
      "Les membres en Communaute ont acces au serveur et participent a la vie collective.",
      "La difference concerne uniquement la visibilite : leurs lives ne sont plus mis en avant automatiquement et leur chaine n'apparait plus dans les outils de promotion.",
      "Ce role n'est pas une sanction.",
      "Il reflete simplement le niveau d'implication actuel.",
      "Le retour en role actif est toujours possible.",
      "Il repose sur une reprise d'engagement concrete dans l'entraide, afin de maintenir un equilibre juste pour tous.",
      "Enfin, certains roles existent pour proteger les plus jeunes :",
      "Les Jeunes Createurs concernent les streamers mineurs.",
      "Les P'tits Jeunes concernent les viewers mineurs.",
      "Cela permet d'adapter l'acces a certains contenus et de garantir un cadre sain et securise.",
      "En resume : les roles evoluent.",
      "Rien n'est fige.",
      "Ici, on avance ensemble - mais l'entraide fonctionne dans les deux sens.",
    ],
    keywords: ["chacun a sa place", "organiser", "pas une sanction", "engagement", "evolution"],
  },
  {
    slug: "spotlight",
    title: "Spotlight New Family",
    emoji: "🎯",
    objectif: "Presenter le systeme phare comme un tremplin collectif.",
    points: [
      "Le Spotlight remplace l'ancien Live Gagnant.",
      "Ce n'est pas un examen: c'est un moment d'authenticite.",
      "Le but est de creer des connexions durables, pas un pic ponctuel.",
      "La reciprocite est essentielle: soutenir aussi les Spotlights des autres.",
    ],
    conseils: [
      "Insister sur la dimension humaine et non performative.",
      "Rappeler que l'acces depend de l'implication et de la reciprocite.",
      "Parler du Spotlight comme d'une opportunite construite ensemble.",
    ],
    discours: [
      "Le Spotlight New Family est le systeme phare de la communaute.",
      "Il a remplace l'ancien concept du Live Gagnant avec une idee tres claire : vous mettre en lumiere, mais dans un cadre structure et collectif.",
      "Le Spotlight n'est pas une simple mise en avant.",
      "C'est un moment organise, pense pour creer de vraies connexions et pas seulement un pic de statistiques.",
      "Pendant une heure, la communaute se rassemble autour de vous pour :",
      "• decouvrir votre univers",
      "• comprendre qui vous etes",
      "• creer du lien durable",
      "• renforcer votre presence dans la communaute",
      "Et c'est important : ce n'est pas un examen.",
      "On ne cherche pas la perfection.",
      "On cherche l'authenticite.",
      "Le but n'est pas de faire \"un gros live d'un soir\".",
      "Le but est de construire des viewers qui resteront et une place solide dans la communaute.",
      "Mais le Spotlight ne fonctionne que si chacun joue son role.",
      "Etre membre actif, c'est aussi soutenir les Spotlights des autres quand vous etes disponibles.",
      "Pas par obligation, pas a chaque fois - mais de maniere reguliere.",
      "La force du systeme repose sur un principe simple :",
      "on ne vient pas seulement pour etre soutenu, on vient aussi pour soutenir.",
      "Le Spotlight est accessible aux membres actifs.",
      "Il s'obtient via l'implication ou la boutique de points, car il repose sur la reciprocite.",
      "Plus vous soutenez les autres, plus la communaute sera naturellement presente pour vous.",
      "Un guide existe pour vous accompagner.",
      "Il est la pour rassurer, structurer et vous permettre de vivre ce moment sereinement.",
      "Le Spotlight est un tremplin collectif.",
      "Pas une competition.",
      "Pas une pression.",
      "Mais une opportunite que l'on construit ensemble.",
    ],
    keywords: ["Spotlight", "authenticite", "collectif", "reciprocite", "lien durable"],
  },
  {
    slug: "evenements",
    title: "Evenements et ecosysteme",
    emoji: "🎉",
    objectif: "Montrer que la New Family depasse largement un simple Discord.",
    points: [
      "Evenements reguliers: film, gaming, defis, formations.",
      "Projets collaboratifs pour renforcer les liens.",
      "Ressources pratiques: guides, OBS, communication, organisation.",
      "Regle cle: ce qui se passe sur Discord reste sur Discord.",
    ],
    conseils: [
      "Donner 2-3 exemples d'evenements recents.",
      "Rappeler la confidentialite des vocaux et soirees internes.",
      "Relier chaque activite a l'objectif d'entraide durable.",
    ],
    discours: [
      "La New Family, ce n'est pas seulement le Spotlight ou un serveur Discord.",
      "C'est un veritable ecosysteme d'entraide structure, pense pour creer du lien, faire evoluer les projets et construire quelque chose sur la duree.",
      "La communaute vit toute l'annee a travers des evenements reguliers : soirees film en petit comite, soirees gaming, defis creatifs, formations et evenements thematiques.",
      "Ces moments ne sont pas obligatoires, mais ils participent a la dynamique collective et renforcent les liens entre membres.",
      "La New Family, ce sont aussi des projets collaboratifs : collabs entre streamers, concepts communs, evenements croises ou idees proposees directement par la communaute.",
      "Ici, l'objectif n'est pas la competition, mais la progression et la connexion durable.",
      "Et parfois, l'aventure depasse le virtuel.",
      "Un projet communautaire important est en preparation : un voyage IRL a PortAventura prevu en mai.",
      "Ce type d'initiative est possible parce que la communaute repose sur des bases solides et des relations sinceres.",
      "Cote ressources et accompagnement, vous trouverez des guides, des formations et des conseils autour du streaming : OBS, communication, organisation, montage et developpement personnel.",
      "L'objectif n'est pas seulement d'augmenter des chiffres, mais de vous aider a construire un projet coherent et durable.",
      "Tout cela repose sur un principe simple :",
      "l'entraide ne s'arrete pas a un live.",
      "Elle se vit au quotidien, dans les echanges, les projets et les moments partages.",
      "Ici, on ne vous laisse pas seuls.",
      "Mais chacun participe a faire vivre cet ecosysteme.",
      "Un point important concernant les evenements communautaires :",
      "tout ce qui se passe sur Discord reste sur Discord.",
      "Les soirees film, les vocaux, les echanges ou les moments internes ne doivent jamais etre diffuses en live Twitch - ni en image, ni en son.",
      "Cela permet de garantir un espace securise, libre et respectueux pour tous les membres.",
      "La confiance est essentielle ici.",
      "Ce cadre protege chacun d'entre nous.",
    ],
    keywords: ["ecosysteme", "entraide", "liens", "ressources", "confidentialite"],
  },
  {
    slug: "vip",
    title: "Force du role VIP",
    emoji: "⭐",
    objectif: "Valoriser l'implication reguliere sans logique de statut social.",
    points: [
      "Le role VIP reconnait la constance et l'etat d'esprit.",
      "Il ne s'achete pas et ne depend pas des stats Twitch.",
      "Le role Contributeur TENF valorise une implication exemplaire du mois.",
      "Ces roles servent la dynamique collective, pas le pouvoir.",
    ],
    conseils: [
      "Bien distinguer reconnaissance et hierarchie.",
      "Insister sur les criteres humains: fiabilite, soutien, regularite.",
      "Rappeler la logique de vote staff pour Contributeur TENF.",
    ],
    discours: [
      "Dans la New Family, l'entraide ne repose pas uniquement sur le staff.",
      "Ce qui fait reellement vivre la communaute au quotidien, ce sont les membres qui s'impliquent naturellement : ceux qui passent sur les lives, qui participent aux evenements, qui prennent quelques minutes pour encourager un autre createur ou accueillir un nouveau.",
      "Ce sont ces gestes simples mais reguliers qui donnent de la force a la communaute.",
      "Pour reconnaitre cet engagement, deux roles existent.",
      "Le premier est le role VIP.",
      "Le VIP ne cree pas une elite.",
      "Il met simplement en lumiere des membres qui montrent une implication reguliere dans la vie de la communaute.",
      "Cela peut etre par leur presence sur les Spotlights, leur participation aux raids, leur soutien aux autres createurs ou leur attitude positive dans les echanges.",
      "Le role VIP ne depend pas des statistiques Twitch et il ne s'achete pas.",
      "Il repose sur quelque chose de beaucoup plus simple : la constance, l'etat d'esprit et la fiabilite dans la communaute.",
      "C'est une maniere de reconnaitre les personnes qui contribuent a maintenir l'equilibre et la dynamique collective.",
      "Nous avons egalement cree un role appele Contributeur TENF.",
      "Ce role a pour objectif de mettre en valeur certains membres qui incarnent particulierement l'esprit de la communaute.",
      "Il s'agit souvent de personnes qui, sans faire partie du staff, participent activement a la vie du serveur :",
      "en accueillant les nouveaux, en animant les discussions, en soutenant regulierement les lives des autres ou en diffusant l'esprit d'entraide de la New Family.",
      "Le role Contributeur TENF est attribue pour une duree d'un mois.",
      "Chaque mois, les trois fondateurs proposent chacun un nom, puis le staff participe a un vote pour selectionner la personne qui recevra ce role.",
      "Pendant cette periode, le membre choisi pourra notamment :",
      "- avoir un acces privilegie a certaines discussions avec le staff",
      "- partager des idees ou des suggestions pour faire evoluer la communaute",
      "- et participer ponctuellement a certaines reflexions autour de la dynamique du serveur.",
      "L'objectif n'est pas de creer un role de pouvoir.",
      "C'est avant tout une maniere de reconnaitre l'engagement humain et de valoriser les personnes qui contribuent a faire vivre l'esprit de la New Family.",
    ],
    keywords: ["VIP", "ne s'achete pas", "regularite", "Contributeur TENF", "engagement humain"],
  },
  {
    slug: "points",
    title: "Points et recompenses",
    emoji: "🪙",
    objectif: "Presenter un systeme ludique qui valorise les bonnes actions.",
    points: [
      "Les points recompensent l'implication, pas la competition.",
      "Les actions utiles du quotidien permettent de gagner des points.",
      "La boutique Spotlight propose des recompenses utiles et fun.",
      "Le bonus journalier et les declarations de raid sont essentiels.",
    ],
    conseils: [
      "Faire une demo simple de la commande journaliere.",
      "Montrer comment declarer un raid pour valoriser l'entraide.",
      "Rappeler que chacun avance a son rythme.",
    ],
    discours: [
      "Dans la New Family, on valorise l'implication concrete.",
      "Chaque action positive que vous faites pour la communaute peut vous rapporter des points.",
      "Pas pour creer un classement, mais pour reconnaitre l'engagement.",
      "Les points se gagnent simplement en vivant la communaute :",
      "- participer aux evenements",
      "- soutenir les membres",
      "- faire des raids internes",
      "- parrainer",
      "- progresser dans l'activite ecrite ou vocale",
      "- suivre les reseaux du serveur",
      "Bref, en faisant ce que l'entraide encourage deja.",
      "Ces points vous donnent ensuite acces a la boutique Spotlight.",
      "On y retrouve des recompenses utiles :",
      "Spotlight complet, analyse de chaine, interview, mise en avant reseaux...",
      "et aussi des elements plus fun.",
      "Ce systeme permet une chose importante :",
      "rendre visible l'implication.",
      "Vous avancez a votre rythme, mais chaque action compte.",
      "Dans un instant, on va voir ensemble comment fonctionne le bonus journalier,",
      "puis comment declarer un raid pour que l'entraide soit reellement valorisee.",
    ],
    keywords: ["points", "engagement", "boutique Spotlight", "bonus journalier", "sans pression"],
  },
  {
    slug: "engagement",
    title: "Engagement TENF",
    emoji: "🤝",
    objectif: "Expliquer l'equilibre entre soutien interne et ouverture externe.",
    points: [
      "Le follow est un premier pas pour decouvrir les univers.",
      "Raider les membres TENF est important, mais rester ouvert l'est aussi.",
      "La New Family est un point d'ancrage, pas une cage.",
      "Au-dela des actions techniques, le lien se construit par l'attitude.",
    ],
    conseils: [
      "Eviter les injonctions: parler d'ouverture et de progression.",
      "Repetir la phrase cle \"point d'ancrage, pas une cage\".",
      "Mettre l'accent sur l'echange sincere dans les chats.",
    ],
    discours: [
      "🌍 Explorer les univers - Le premier pas",
      "S'integrer dans la New Family commence par une chose simple :",
      "decouvrir les autres createurs.",
      "Concretement, cela passe par un premier geste :",
      "👉 suivre les chaines des membres actifs.",
      "Pourquoi ?",
      "Parce que le follow ici n'est pas un echange automatique.",
      "C'est un point de depart.",
      "Il vous permet :",
      "- d'identifier les createurs",
      "- de recevoir leurs notifications",
      "- de decouvrir progressivement leurs univers",
      "- et de creer des liens reels avec le temps",
      "On ne vous demande pas d'aimer tout le monde.",
      "On ne vous demande pas d'etre presents partout.",
      "On vous demande d'ouvrir la porte.",
      "Le follow est un outil de connexion, pas une monnaie d'echange.",
      "💜 Raidez la New Family... mais restez ouverts",
      "Raider les membres de la Family est un pilier important.",
      "Cela renforce les liens, soutient les projets et donne de la coherence au systeme.",
      "Mais la New Family n'est pas une bulle fermee.",
      "👉 Vous pouvez - et devez - aussi raider en dehors.",
      "Creer des ponts avec d'autres communautes est sain.",
      "Cela permet :",
      "- d'elargir votre reseau",
      "- de faire decouvrir la Family a l'exterieur",
      "- de garder une dynamique naturelle",
      "La New Family est un point d'ancrage, pas une cage.",
      "💬 Au-dela du follow et du raid",
      "Ce qui compte vraiment, ce n'est pas le bouton \"suivre\".",
      "C'est l'echange.",
      "Une attitude respectueuse.",
      "Une presence sincere.",
      "Un soutien naturel.",
      "Le follow est le premier pas.",
      "Le lien se construit ensuite.",
    ],
    keywords: ["follow", "connexion", "raid", "point d'ancrage", "echange"],
  },
  {
    slug: "progression",
    title: "Conseils progression TENF",
    emoji: "📈",
    objectif: "Donner une methode simple pour progresser naturellement.",
    points: [
      "Participer aux discussions ecrites/vocales et aux Spotlights.",
      "Aider les nouveaux et partager son experience.",
      "La difference se fait sur la regularite et la fiabilite.",
      "Pas de course: chacun contribue selon son rythme.",
    ],
    conseils: [
      "Valoriser les petits gestes repetes plutot que les coups d'eclat.",
      "Recadrer gentiment les attentes de resultats immediats.",
      "Conclure sur la constance et la qualite des interactions.",
    ],
    discours: [
      "Comment progresser naturellement dans la New Family ?",
      "S'integrer et evoluer ici repose sur des actions simples et concretes.",
      "Ce que tu peux faire :",
      "• Participer aux discussions ecrites ou vocales",
      "• Etre present aux Spotlights quand tu es disponible",
      "• Faire des raids internes",
      "• Accueillir et aider les nouveaux membres",
      "• Partager ton experience si elle peut etre utile",
      "• Participer aux evenements communautaires",
      "Rien d'extraordinaire.",
      "Juste une presence coherente.",
      "Ce qui fait reellement la difference :",
      "• Ta regularite",
      "• Ta fiabilite",
      "• Ton respect du cadre",
      "• Ton attitude dans les echanges",
      "• Ta capacite a soutenir sans attendre immediatement un retour",
      "L'implication ne se mesure pas uniquement a des statistiques.",
      "Elle se voit dans la constance et dans la qualite des interactions.",
      "Ici, il n'y a pas de course.",
      "Mais il y a une dynamique collective.",
      "Chacun avance a son rythme,",
      "mais chacun contribue a l'equilibre du groupe.",
    ],
    keywords: ["regularite", "fiabilite", "constance", "pas de course", "dynamique collective"],
  },
  {
    slug: "invitation",
    title: "Inviter de nouveaux membres",
    emoji: "📨",
    objectif: "Expliquer une croissance maitrisee basee sur la qualite humaine.",
    points: [
      "La croissance repose sur la recommandation de confiance.",
      "Verifier l'alignement avec l'esprit entraide et respect.",
      "Parcours d'entree: reglement, role, reunion d'integration.",
      "Chaque nouveau membre influence l'equilibre du groupe.",
    ],
    conseils: [
      "Parler de croissance maitrisee plutot que de volume.",
      "Insister sur le role protecteur du processus d'integration.",
      "Faire reformuler les 3 etapes d'entree par les nouveaux.",
    ],
    discours: [
      "Comment la New Family grandit ?",
      "La New Family ne grandit pas par publicite massive.",
      "Elle grandit parce que ses membres invitent des personnes en qui ils ont confiance.",
      "Nous privilegions la qualite humaine plutot que la quantite.",
      "Si vous souhaitez inviter quelqu'un, posez-vous simplement une question :",
      "👉 Est-ce que cette personne partage l'esprit d'entraide et de respect ?",
      "Si la reponse est oui, alors expliquez-lui :",
      "- de lire le reglement en arrivant",
      "- de choisir son role pour trouver sa place",
      "- de participer a la reunion d'integration",
      "Ce processus existe pour proteger la communaute, pas pour filtrer arbitrairement.",
      "Chaque nouveau membre influence l'equilibre du groupe.",
      "C'est pour cela que nous grandissons de maniere maitrisee.",
      "Nous cherchons des personnes qui veulent construire, pas seulement consommer.",
      "La New Family avance parce que ses membres s'impliquent - et transmettent cet esprit autour d'eux.",
    ],
    keywords: ["confiance", "qualite humaine", "reglement", "integration", "equilibre"],
  },
  {
    slug: "final",
    title: "Conclusion et prochaines etapes",
    emoji: "🏁",
    objectif: "Cloturer clairement, ouvrir aux questions et lancer les actions post-reunion.",
    points: [
      "Prendre un temps final de questions/reponses.",
      "Annoncer les prochaines etapes d'integration.",
      "Presenter le site officiel teamnewfamily.netlify.app.",
      "Conclure sur l'implication humaine et l'accueil officiel.",
    ],
    conseils: [
      "Ralentir le rythme pour une fin claire et rassurante.",
      "Verifier que chacun sait quoi faire apres la reunion.",
      "Terminer sur une phrase positive et mobilisatrice.",
    ],
    discours: [
      "Et voila, on arrive a la fin de cette reunion d'integration.",
      "Merci d'avoir pris le temps d'etre presents, d'avoir ecoute et pose vos questions.",
      "Rejoindre la New Family, ce n'est pas anodin - et votre presence aujourd'hui montre votre envie de faire partie du collectif.",
      "Avant de conclure, on ouvre un dernier temps d'echange.",
      "Si vous avez des questions sur le fonctionnement, les roles, les points, le Spotlight ou l'organisation generale, c'est le moment.",
      "Le micro est ouvert, et vous pouvez aussi ecrire dans le salon juste en dessous.",
      "(Prendre quelques minutes pour repondre calmement)",
      "Prochaines etapes",
      "Dans les prochaines heures - au plus tard d'ici demain :",
      "✔ votre role actif sera attribue",
      "✔ votre chaine sera ajoutee a la liste interne des membres actifs",
      "✔ vous serez integres au systeme d'entraide",
      "L'ajout sur le site web se fait lors de la mise a jour hebdomadaire en fin de semaine.",
      "Si vous ne vous voyez pas immediatement, c'est normal.",
      "Le site web de la New Family",
      "Avant de terminer, on vous montre rapidement notre site officiel :",
      "teamnewfamily.netlify.app",
      "Ce site centralise :",
      "📚 La documentation et les ressources",
      "🎯 Les prochains Spotlights",
      "👥 La presentation de l'equipe",
      "🎮 La liste des createurs actifs",
      "🔴 Les lives en cours",
      "Il reflete notre fonctionnement : structure, transparence et accessibilite.",
      "(Faire une demo rapide et dynamique, sans trop detailler)",
      "A partir de maintenant, vous faites partie de la dynamique.",
      "Explorez les univers.",
      "Passez sur les lives quand vous etes disponibles.",
      "Participez aux echanges.",
      "Utilisez les outils.",
      "La New Family fonctionne sur la coherence et l'implication humaine.",
      "Vous n'etes pas obliges de tout faire tout de suite.",
      "Mais chaque pas compte.",
      "Bienvenue officiellement dans la New Family.",
      "On est sincerement heureux de vous compter parmi nous. 💜",
    ],
    keywords: ["questions", "prochaines etapes", "site officiel", "bienvenue", "chaque pas compte"],
  },
];
